module.exports = {
  src: [
    './src/api_client.ts',
    './src/resources/accounts.ts',
    './src/resources/dapps.ts',
    './src/resources/blocks.ts',
    './src/resources/delegates.ts',
    './src/resources/node.ts',
    './src/resources/peers.ts',
    './src/resources/signatures.ts',
    './src/resources/transactions.ts',
    './src/resources/voters.ts',
    './src/resources/votes.ts',
  ],
  mode: 'file',
  exclude: [
        '**/__test__/**/*',
        '**/__node_modules__/**/*',
    ],
  includeDeclarations: true,
  externalPattern: '**/node_modules/**',
  excludeExternals: true,
  excludeNotExported: true,
  tsconfig: './tsconfig.json',
  out: '../../../typedocs/api-client2',
  ignoreCompilerErrors: true,
  plugin: 'none',
  readme: 'none',
  theme: 'markdown',
};
